<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Deterministic>false</Deterministic>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\AssemblyInfo.cs" Link="AssemblyInfo.cs" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
		<PackageReference Include="IdentityServer4.AccessTokenValidation" Version="3.0.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.0" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.7.0" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.7.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.6" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Common\Common.csproj" />
		<ProjectReference Include="..\DataAccess\DataAccess.csproj" />
	</ItemGroup>

</Project>
