<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Deterministic>false</Deterministic>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6" />
	</ItemGroup>
	<ItemGroup>
		<Compile Include="..\AssemblyInfo.cs" Link="AssemblyInfo.cs" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Common\Common.csproj" />
	</ItemGroup>


	<ItemGroup>
	  <Folder Include="DbContexts\InventoryManagement\Models\" />
	</ItemGroup>
</Project>
